version: '3.3'

volumes:
  logs:
    driver: local

services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    links:
      - slim
    restart: always
    environment:
      DOMAINS: 'goukon.f5.si -> http://slim'
      STAGE: 'production'
      # FORCE_RENEW: 'true'

  slim:
      build:
        context: .
        dockerfile: ./php/Dockerfile

  mysql:
      image: mysql:8.0
      env_file:
        - .env
      environment:
        MYSQL_USER: goukon
        MYSQL_DATABASE: goukon
        TZ: "Asia/Tokyo"
        BIND-ADDRESS: 0.0.0.0
      volumes:
        - ./mysql/mysql_conf:/etc/mysql/conf.d
          #- ./mysql/mysql_init:/docker-entrypoint-initdb.d
      ports:
        - 3306:3306
