version: '3.3'

volumes:
  logs:
    driver: local

services:
  slim:
      build:
        context: .
        dockerfile: ./php/Dockerfile
      ports:
        - 80:80

  mysql:
      image: mysql:8.0
      env_file:
        - .env
      environment:
        TZ: "Asia/Tokyo"
        BIND-ADDRESS: 0.0.0.0
      volumes:
        - ./mysql/mysql_conf:/etc/mysql/conf.d
        - ./mysql/mysql_init:/docker-entrypoint-initdb.d
      ports:
        - 3306:3306
